[package]
name = "usb-host"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
flexi_logger = "0.29.7"
log = "0.4.22"
futures-lite = "2.5.0"
rusb = "0.9.4"
usb-ids = "1.2024.5"
image = "0.25.5"
mbi5264-common = { path = "../mbi5264-common" }
