[package]
name = "img_buider"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
image = "0.25.0"
vdrm-alg = { path = "/Users/hikari/rust/vdrm/vdrm-alg/" }
# vdrm-alg = { git = "https://github.com/hikaricai/vdrm.git", package = "vdrm-alg", branch = "master" }
mbi5264-common = { path = "../../mbi5264-common" }
